name: Android CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Download keystore
        env:
          PHISH_TAPES_ENCODED_KEY: ${{ secrets.PHISH_TAPES_ENCODED_KEY }}
        run: |
          mkdir -p keys
          echo -n "$PHISH_TAPES_ENCODED_KEY" | base64 --decode > keys/release.jks

      - name: Set up signing properties in gradle.properties
        run: |
          echo "phish.tapes.keystorePassword=${{ secrets.PHISH_TAPES_KEYSTORE_PASSWORD }}" >> gradle.properties
          echo "phish.tapes.aliasKeyPassword=${{ secrets.PHISH_TAPES_KEY_PASSWORD }}" >> gradle.properties
          echo "phish.tapes.storeKeyAlias=${{ secrets.PHISH_TAPES_KEY_ALIAS }}" >> gradle.properties
          echo "phish.tapes.keystoreLocation=$(pwd)/keys/release.jks" >> gradle.properties

      - name: Set build number in gradle.properties
        run: |
          DEFAULT_BUILD_NUMBER=$(grep '^phish.tapes.defaultBuildNumber=' gradle.properties | cut -d'=' -f2)
          BUILD_NUMBER=$((DEFAULT_BUILD_NUMBER + 1))

      - name: Build with Gradle (using gradle/actions)
        uses: gradle/actions/setup-gradle@v4

      - name: Build signed APKs and AABs (debug and release)
        run: ./gradlew build bundleDebug bundleRelease --no-daemon -Pphish.tapes.buildNumber=$BUILD_NUMBER

      - name: Import GPG key
        env:
          PHISH_TAPES_PGP_KEY: ${{ secrets.PGP_KEY }}
          PHISH_TAPES_PGP_PASSWORD: ${{ secrets.PGP_PASSWORD }}
        run: |
          echo "$PHISH_TAPES_PGP_KEY" > private.key
          gpg --batch --passphrase "$PHISH_TAPES_PGP_PASSWORD" --import private.key

      - name: Sign APKs and AABs with GPG
        env:
          PHISH_TAPES_PGP_PASSWORD: ${{ secrets.PGP_PASSWORD }}
        run: |
          for file in build/outputs/apk/debug/*.apk build/outputs/apk/release/*.apk build/outputs/bundle/debug/*.aab build/outputs/bundle/release/*.aab; do
            if [ -f "$file" ]; then
              gpg --batch --yes --pinentry-mode loopback --passphrase "$PHISH_TAPES_PGP_PASSWORD" --armor --detach-sign "$file"
            fi
          done

      - name: Upload APK, AAB, and ASC as workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: |
            build/outputs/apk/debug/*.apk
            build/outputs/apk/debug/*.apk.asc
            build/outputs/apk/release/*.apk
            build/outputs/apk/release/*.apk.asc
            build/outputs/bundle/debug/*.aab
            build/outputs/bundle/debug/*.aab.asc
            build/outputs/bundle/release/*.aab
            build/outputs/bundle/release/*.aab.asc

      - name: Upload to Google Play (Internal Test Track)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PHISH_TAPES_PUBLISH_KEY }}
          packageName: rocks.ghostapps.phishtapes
          releaseFiles: build/outputs/bundle/release/*.aab
          track: internal
          status: completed

      - name: Update phish.tapes.defaultBuildNumber in gradle.properties on success
        if: success()
        run: |
          sed -i.bak "s/^phish.tapes.defaultBuildNumber=.*/phish.tapes.defaultBuildNumber=$BUILD_NUMBER/" gradle.properties
          rm gradle.properties.bak
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add gradle.properties
          git commit -m "chore: update phish.tapes.defaultBuildNumber to $BUILD_NUMBER [skip ci]" || echo "No changes to commit"
          git push || echo "No push performed (possibly running on a fork)"
