name: Publish to Playstore
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'
          bundler-cache: true
      - name: Setup Fastlane
        run: bundle install
      - name: Retrieve Key File
        env:
          PHISH_TAPES_ENCODED_KEY: ${{ secrets.PHISH_TAPES_ENCODED_KEY }}
        run: echo -n $PHISH_TAPES_ENCODED_KEY | base64 --decode > ./keys/release.jks
      - name: Provide Publish Key
        env:
          PHISH_TAPES_PUBLISH_KEY: ${{ secrets.PHISH_TAPES_PUBLISH_KEY }}
        run: echo $PHISH_TAPES_PUBLISH_KEY > ./keys/phish-tapes-play-key.json
      - name: Create Build Number
        run: |
          BUILD_NUMBER=$((GITHUB_RUN_NUMBER + 2000357810))
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
      - name: Build and Publish to Beta Track
        env:
          PHISH_TAPES_KEYSTORE_PASSWORD: ${{ secrets.PHISH_TAPES_KEYSTORE_PASSWORD }}
          PHISH_TAPES_KEY_ALIAS: ${{ secrets.PHISH_TAPES_KEY_ALIAS }}
          PHISH_TAPES_KEY_PASSWORD: ${{ secrets.PHISH_TAPES_KEY_PASSWORD }}
          PHISH_TAPES_PHISHIN_API_KEY: ${{ secrets.PHISH_TAPES_PHISHIN_API_KEY }}
          PHISH_TAPES_PHISH_NET_API_KEY: ${{ secrets.PHISH_TAPES_PHISH_NET_API_KEY }}
          PHISH_TAPES_KEYSTORE_LOCATION: ./keys/release.jks
          PHISH_TAPES_BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
          PHISH_TAPES_ACCEPT_BUILD_SCAN_AGREEMENT: yes
        run: bundle exe fastlane beta
